apiVersion: v1
kind: ConfigMap
metadata:
  name: marrano-config
data:
  WEBHOOK: "https://bot.marrani.lol"
  WEBHOOK_SECRET: "test"
  DATABASE_FILE: "/data/db.sqlite"
  TELEGRAM_TOKEN: "DEADBEEF:123456"
  PORT: 10000
---
apiVersion: v1
kind: Pod
metadata:
  name: marrano-bot
spec:
  containers:
  - name: bot
    image: docker.io/moolite/bot
    volumeMounts:
      - name: db-storage
        mountPath: /data/
    envFrom:
    - configMapRef:
        name: marrano-config
        optional: false
  volumes:
  - name: db-storage
    hostPath:
      path: db
      type: DirectoryOrCreate
