name: ci

on:
  workflow_dispatch:
  push:
    branches:
      - "github-action"
      - "master"
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # - name: bootstrap nix

      # - name: Create release
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #     ref: ${{ github.ref_name }}
      #     version: ${{ steps.uberjar.outputs.version }}
      #     TARGET: ${{ steps.uberjar.outputs.target }}
      #   run: |
      #     gh release create \
      #         --repo="$GITHUB_REPOSITORY" \
      #         --title="snapshot ${version#v}" \
      #         --generate-notes \
      #         "${version#v}" \
      #         ./${TARGET}
